INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (1, 'Afghanistan', 'AFN', 'AF');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (2, 'Albania', 'ALL', 'AL');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (3, 'Algeria', 'DZD', 'DZ');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (4, 'Andorra', 'EUR', 'AD');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (5, 'Angola', 'AOA', 'AO');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (6, 'Argentina', 'ARS', 'AR');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (7, 'Armenia', 'AMD', 'AM');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (8, 'Australia', 'AUD', 'AU');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (9, 'Austria', 'EUR', 'AT');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (10, 'Azerbaijan', 'AZN', 'AZ');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (11, 'Bahamas', 'BSD', 'BS');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (12, 'Bahrain', 'BHD', 'BH');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (13, 'Bangladesh', 'BDT', 'BD');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (14, 'Belarus', 'BYN', 'BY');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (15, 'Belgium', 'EUR', 'BE');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (16, 'Belize', 'BZD', 'BZ');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (17, 'Benin', 'XOF', 'BJ');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (18, 'Bhutan', 'BTN', 'BT');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (19, 'Bolivia', 'BOB', 'BO');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (20, 'Bosnia and Herzegovina', 'BAM', 'BA');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (21, 'Botswana', 'BWP', 'BW');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (22, 'Brazil', 'BRL', 'BR');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (23, 'Brunei', 'BND', 'BN');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (24, 'Bulgaria', 'BGN', 'BG');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (25, 'Burkina Faso', 'XOF', 'BF');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (26, 'Burundi', 'BIF', 'BI');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (27, 'Cambodia', 'KHR', 'KH');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (28, 'Cameroon', 'XAF', 'CM');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (29, 'Canada', 'CAD', 'CA');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (30, 'Cape Verde', 'CVE', 'CV');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (31, 'Central African Republic', 'XAF', 'CF');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (32, 'Chad', 'XAF', 'TD');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (33, 'Chile', 'CLP', 'CL');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (34, 'China', 'CNY', 'CN');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (35, 'Colombia', 'COP', 'CO');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (36, 'Comoros', 'KMF', 'KM');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (37, 'Congo (Brazzaville)', 'XAF', 'CG');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (38, 'Congo (Kinshasa)', 'CDF', 'CD');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (39, 'Costa Rica', 'CRC', 'CR');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (40, 'Croatia', 'EUR', 'HR');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (41, 'Cuba', 'CUP', 'CU');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (42, 'Cyprus', 'EUR', 'CY');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (43, 'Czech Republic', 'CZK', 'CZ');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (44, 'Denmark', 'DKK', 'DK');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (45, 'Djibouti', 'DJF', 'DJ');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (46, 'Dominica', 'XCD', 'DM');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (47, 'Dominican Republic', 'DOP', 'DO');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (48, 'Ecuador', 'USD', 'EC');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (49, 'Egypt', 'EGP', 'EG');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (50, 'El Salvador', 'USD', 'SV');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (51, 'Equatorial Guinea', 'XAF', 'GQ');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (52, 'Eritrea', 'ERN', 'ER');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (53, 'Estonia', 'EUR', 'EE');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (54, 'Eswatini', 'SZL', 'SZ');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (55, 'Ethiopia', 'ETB', 'ET');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (56, 'Fiji', 'FJD', 'FJ');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (57, 'Finland', 'EUR', 'FI');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (58, 'France', 'EUR', 'FR');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (59, 'Gabon', 'XAF', 'GA');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (60, 'Gambia', 'GMD', 'GM');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (61, 'Georgia', 'GEL', 'GE');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (62, 'Germany', 'EUR', 'DE');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (63, 'Ghana', 'GHS', 'GH');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (64, 'Greece', 'EUR', 'GR');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (65, 'Grenada', 'XCD', 'GD');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (66, 'Guatemala', 'GTQ', 'GT');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (67, 'Guinea', 'GNF', 'GN');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (68, 'Guinea-Bissau', 'XOF', 'GW');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (69, 'Guyana', 'GYD', 'GY');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (70, 'Haiti', 'HTG', 'HT');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (71, 'Honduras', 'HNL', 'HN');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (72, 'Hungary', 'HUF', 'HU');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (73, 'Iceland', 'ISK', 'IS');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (74, 'India', 'INR', 'IN');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (75, 'Indonesia', 'IDR', 'ID');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (76, 'Iran', 'IRR', 'IR');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (77, 'Iraq', 'IQD', 'IQ');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (78, 'Ireland', 'EUR', 'IE');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (79, 'Israel', 'ILS', 'IL');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (80, 'Italy', 'EUR', 'IT');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (81, 'Jamaica', 'JMD', 'JM');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (82, 'Japan', 'JPY', 'JP');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (83, 'Jordan', 'JOD', 'JO');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (84, 'Kazakhstan', 'KZT', 'KZ');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (85, 'Kenya', 'KES', 'KE');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (86, 'Kiribati', 'AUD', 'KI');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (87, 'Kuwait', 'KWD', 'KW');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (88, 'Kyrgyzstan', 'KGS', 'KG');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (89, 'Laos', 'LAK', 'LA');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (90, 'Latvia', 'EUR', 'LV');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (91, 'Lebanon', 'LBP', 'LB');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (92, 'Lesotho', 'LSL', 'LS');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (93, 'Liberia', 'LRD', 'LR');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (94, 'Libya', 'LYD', 'LY');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (95, 'Liechtenstein', 'CHF', 'LI');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (96, 'Lithuania', 'EUR', 'LT');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (97, 'Luxembourg', 'EUR', 'LU');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (98, 'Madagascar', 'MGA', 'MG');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (99, 'Malawi', 'MWK', 'MW');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (100, 'Malaysia', 'MYR', 'MY');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (101, 'Maldives', 'MVR', 'MV');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (102, 'Mali', 'XOF', 'ML');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (103, 'Malta', 'EUR', 'MT');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (104, 'Marshall Islands', 'USD', 'MH');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (105, 'Mauritania', 'MRU', 'MR');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (106, 'Mauritius', 'MUR', 'MU');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (107, 'Mexico', 'MXN', 'MX');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (108, 'Micronesia', 'USD', 'FM');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (109, 'Moldova', 'MDL', 'MD');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (110, 'Monaco', 'EUR', 'MC');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (111, 'Mongolia', 'MNT', 'MN');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (112, 'Montenegro', 'EUR', 'ME');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (113, 'Morocco', 'MAD', 'MA');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (114, 'Mozambique', 'MZN', 'MZ');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (115, 'Myanmar', 'MMK', 'MM');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (116, 'Namibia', 'NAD', 'NA');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (117, 'Nauru', 'AUD', 'NR');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (118, 'Nepal', 'NPR', 'NP');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (119, 'Netherlands', 'EUR', 'NL');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (120, 'New Zealand', 'NZD', 'NZ');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (121, 'Nicaragua', 'NIO', 'NI');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (122, 'Niger', 'XOF', 'NE');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (123, 'Nigeria', 'NGN', 'NG');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (124, 'North Korea', 'KPW', 'KP');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (125, 'North Macedonia', 'MKD', 'MK');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (126, 'Norway', 'NOK', 'NO');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (127, 'Oman', 'OMR', 'OM');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (128, 'Pakistan', 'PKR', 'PK');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (129, 'Palau', 'USD', 'PW');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (130, 'Palestine', 'ILS', 'PS');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (131, 'Panama', 'PAB', 'PA');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (132, 'Papua New Guinea', 'PGK', 'PG');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (133, 'Paraguay', 'PYG', 'PY');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (134, 'Peru', 'PEN', 'PE');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (135, 'Philippines', 'PHP', 'PH');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (136, 'Poland', 'PLN', 'PL');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (137, 'Portugal', 'EUR', 'PT');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (138, 'Qatar', 'QAR', 'QA');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (139, 'Romania', 'RON', 'RO');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (140, 'Russia', 'RUB', 'RU');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (141, 'Rwanda', 'RWF', 'RW');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (142, 'Saint Kitts and Nevis', 'XCD', 'KN');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (143, 'Saint Lucia', 'XCD', 'LC');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (144, 'Saint Vincent and the Grenadines', 'XCD', 'VC');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (145, 'Samoa', 'WST', 'WS');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (146, 'San Marino', 'EUR', 'SM');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (147, 'Sao Tome and Principe', 'STN', 'ST');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (148, 'Saudi Arabia', 'SAR', 'SA');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (149, 'Senegal', 'XOF', 'SN');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (150, 'Serbia', 'RSD', 'RS');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (151, 'Seychelles', 'SCR', 'SC');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (152, 'Sierra Leone', 'SLL', 'SL');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (153, 'Singapore', 'SGD', 'SG');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (154, 'Slovakia', 'EUR', 'SK');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (155, 'Slovenia', 'EUR', 'SI');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (156, 'Solomon Islands', 'SBD', 'SB');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (157, 'Somalia', 'SOS', 'SO');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (158, 'South Africa', 'ZAR', 'ZA');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (159, 'South Korea', 'KRW', 'KR');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (160, 'South Sudan', 'SSP', 'SS');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (161, 'Spain', 'EUR', 'ES');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (162, 'Sri Lanka', 'LKR', 'LK');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (163, 'Sudan', 'SDG', 'SD');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (164, 'Suriname', 'SRD', 'SR');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (165, 'Sweden', 'SEK', 'SE');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (166, 'Switzerland', 'CHF', 'CH');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (167, 'Syria', 'SYP', 'SY');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (168, 'Taiwan', 'TWD', 'TW');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (169, 'Tajikistan', 'TJS', 'TJ');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (170, 'Tanzania', 'TZS', 'TZ');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (171, 'Thailand', 'THB', 'TH');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (172, 'Timor-Leste', 'USD', 'TL');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (173, 'Togo', 'XOF', 'TG');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (174, 'Tonga', 'TOP', 'TO');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (175, 'Trinidad and Tobago', 'TTD', 'TT');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (176, 'Tunisia', 'TND', 'TN');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (177, 'Turkey', 'TRY', 'TR');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (178, 'Turkmenistan', 'TMT', 'TM');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (179, 'Tuvalu', 'AUD', 'TV');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (180, 'Uganda', 'UGX', 'UG');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (181, 'Ukraine', 'UAH', 'UA');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (182, 'United Arab Emirates', 'AED', 'AE');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (183, 'United Kingdom', 'GBP', 'GB');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (184, 'United States', 'USD', 'US');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (185, 'Uruguay', 'UYU', 'UY');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (186, 'Uzbekistan', 'UZS', 'UZ');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (187, 'Vanuatu', 'VUV', 'VU');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (188, 'Vatican City', 'EUR', 'VA');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (189, 'Venezuela', 'VES', 'VE');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (190, 'Vietnam', 'VND', 'VN');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (191, 'Yemen', 'YER', 'YE');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (192, 'Zambia', 'ZMW', 'ZM');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (193, 'Zimbabwe', 'ZWL', 'ZW');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (194, 'Kosovo', 'EUR', 'XK');
INSERT INTO "country" ("id", "name", "currency", "country_code") VALUES (195, 'Western Sahara', 'MAD', 'EH');

